name: buildx-push-action
description: build and push a Docker image using buildx
inputs:
  cache:
    description: buildx cache directory
    required: true
    default: /tmp/buildx
  repository:
    description: repository to push
    required: true
    default: ghcr.io/${{ github.repository }}
  iidfile:
    description: file to write the image ID
    required: true
    default: /tmp/iidfile
  working-directory:
    description: working directory where the action is run
    required: false
  extra-args:
    description: extra arguments to pass to `docker buildx build`
    required: false
outputs:
  digest:
    description: image digest
    value: ${{ steps.exec.outputs.iidfile }}
  image:
    description: image tag with the digest
    value: ${{ inputs.repository }}@${{ steps.exec.outputs.iidfile }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/exec.sh ${{ inputs.extra-args }}
      env:
        CACHE_DIRECTORY: ${{ inputs.cache }}
        DOCKER_REPOSITORY: ${{ inputs.repository }}
        IIDFILE: ${{ inputs.iidfile }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      id: exec
